### ISSUE TITLE
mapsort is same function for `sortBy` as other language.

### ISSUE THREAD

**Issue by xp44mm** [Pimm/mapsort#4]
same as title.

**Comment by Pimm** [comment]
Hi @xp44mm,

It is conceptually similar to Lodash' `sortBy`, yes. `mapSort` is `_.sortBy`'s faster, smaller, and more standards-conforming sister.

It is also similar to [sorting by key function](https://wiki.python.org/moin/HowTo/Sorting#Key_Functions) in Python.
