### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by dreplica** [Pimm/mapsort#7]
Hi, @Pimm 

There's a typo on the README.md.
```
   Sorting them with no compare function would place `'12.4'` before `'3.35'`, so we need `a such a` function:
```

I would like to contribute by fixing this typo to:

```
Sorting them with no compare function would place `'12.4'` before `'3.35'`, so we need `such a` function:
```

**Comment by Pimm** [comment]
Thank you!

If you open a PR, I'll merge it and you'll be listed as a contributor. If you don't want to go through all of that trouble, I'll do it myself. Whichever you prefer.

**Comment by dreplica** [comment]
I tried to make a PR but said I have no permission

**Comment by Pimm** [comment]
You would have to fork first.

Again, if you don't want to do all that, I'll fix the typo myself. No problem.

**Comment by dreplica** [comment]
Hi, please review the PR made
